<?php
#API RESPONSE CODES
define('API_RES_STATUS_SUCCESS', 200);
define('API_RES_STATUS_NO_CONTENT', 204);
define('API_RES_STATUS_INTERNAL_SERVER_ERROR', 500);
define('API_RES_STATUS_BAD_REQUEST', 400);
define('API_RES_STATUS_FORBIDDEN_ERROR', 403);
define('API_RES_STATUS_NOT_FOUND_ERROR', 404);
define('API_RES_STATUS_METHOD_NOT_ALLOWED', 405);
define('API_RES_STATUS_UNAUTHORIZED', 401);
define('API_RES_STATUS_INVALID_TOKEN', 401);

